services:

  snapfile:
    restart: unless-stopped
    container_name: snapfile
    build: .
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - TZ=${DOCKER_TZ}
      - MAX_FILE_SIZE=524288000  # 500 MB in bytes = 500 * 1024 * 1024
      - MAX_USES_PER_DAY=5
      - INTERNAL_IP=127.0.0.1
      - INTERNAL_PORT=8080
    volumes:
      - /snapfile/uploads:/app/uploads
      - /snapfile/database:/app/database

