FROM ghcr.io/remimikalsen/python-testbed:v1 AS base

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY requirements-dev.txt .
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY app/ ./app
COPY VERSION ./app
COPY tests/ ./tests
COPY pytest.ini .
COPY pyproject.toml .


COPY tests-dockerized/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Default command if none
CMD []
